### ISSUE TITLE
README

### ISSUE THREAD

**Issue by unnamedd** [marcodiniz/TinBot#1]
Hey @marcodiniz,

acabei de receber o vídeo no YouTube sobre o TinBot. Muito maneiro a iniciativa, parabéns, porém, já que você publicou o código como open source, seria interessante se você criasse um README mais completinho de forma que instruísse quem quisesse executar o seu código ou mesmo tentar recriar o TinBot. 

O que você acha ? Será que vale a sugestão ?

Parabéns mais uma vez!

**Comment by marcodiniz** [comment]
Opa.
Sim, realmente.
Vou tentar essa semana ainda fazer isso e subir outras coisas no código pra deixar mais fácil!
Também preciso disponibilizar o desenho dos circuitos, mas ainda não existem esses desenhos rs.

Vlw! =]
